---
version: '3'
services:
  freqtrade:
    build:
       context: .
       dockerfile: "./Dockerfile"
    env_file: 
      - .env
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
       - "127.0.0.1:8080:8080"
    command: ./run.sh
