---
version: '3'
services:
  live:
    image: joaoraf/freqtrade:master
    env_file: 
      - .env
    restart: unless-stopped
    volumes:
      - "./db:/freqtrade/db"
    command: >
      freqtrade trade -c live.json

  dry:
    image: joaoraf/freqtrade:master
    env_file: 
      - .env
    restart: unless-stopped
    volumes:
      - "./db:/freqtrade/db"
    command: >
      freqtrade trade -c dry.json
